### ISSUE TITLE
Not add package from NuGet

### ISSUE THREAD

**Issue by Sanysvo** [0blu/PhotonPackageParser#7]
Не удалось установить пакет «PhotonPackageParser 4.0.0». Вы пытаетесь установить этот пакет в проект, требуемая версия платформы которого — «.NETFramework,Version=v4.5.2», но в пакете нет ссылок на сборки или файлов содержимого, совместимых с этой платформой. Дополнительную информацию можно получить у автора пакета.

**Comment by DocTi** [comment]
Версия проекта должна быть 4.5.2

У вас какая?

**Comment by Sanysvo** [comment]
Такая и есть. Поставил 4.7.2 и сразу добавилось

**Comment by 0blu** [comment]
@DocTi Thanks for providing support. Is this issue fixed? Google translator is kinda ambiguous :/

**Comment by DocTi** [comment]
@0blu Yes
