### ISSUE TITLE
Event code issue

### ISSUE THREAD

**Issue by horan74** [0blu/PhotonPackageParser#8]
Hello!

I'm trying to use your example. The game "Albion Online" is running.

```
protected override void OnEvent(byte code, Dictionary<byte, object> parameters)
{
     Console.WriteLine("Event " + code);
}
```

The command's line output is always "Event 1" or "Event 2".

What's wrong?

**Comment by DocTi** [comment]
To get the event code use this example code:
```
parameters.TryGetValue(252, out var value);
```

**Comment by DocTi** [comment]
To get the operation code use this example code:
```
parameters.TryGetValue(253, out var value);
```

**Comment by 0blu** [comment]
You might want to take a look into this code
https://github.com/0blu/AlbionTracker/blob/45487b2603f99756466703191617ddd3319a718d/AlbionNetworkAnalyzer/AlbionContractParser.cs#L73
https://github.com/0blu/AlbionTracker/blob/45487b2603f99756466703191617ddd3319a718d/AlbionNetworkAnalyzer/AlbionContractParser.cs#L111

**Comment by horan74** [comment]
> To get the event code use this example code:
> 
> ```
> parameters.TryGetValue(252, out var value);
> ```

Thank you very match! The events and operations decode successfuly!
